class AdminController < ApplicationController
  def init
    Site.create domain: "local", itskey: "local", mykey: "local"
    Site.create domain: "localhost", itskey: "key1", mykey: "key1"
    ApplicationSetting.create vote_timeline: 7, vote_min_valid: 100
    User.create name: "a", passwd: "$2a$12$4UGpnS3d5otoGi0OCEBovecxhJui2k3iClGbON.8RLU3vuBXuFkD.", voter_hash: "4bba9931c0b8ff4055f8b104fbc26818"
    quests = ["What shows are you into?",
"What’s your claim to fame?",
"How often do you play sports?",
"Are you usually early or late?",
"What quirks do you have?",
"How often do you people watch?",
"What’s your favorite drink?",
"What do you hope never changes?",
"What’s your dream car?",
"Where would you rather be from?",
"What songs have you completely memorized?",
"What would you rate 10 / 10?",
"What job would you be terrible at?",
"What are you absolutely determined to do?",
"What skill would you like to master?",
"What website do you visit most often?",
"What would your perfect room look like?",
"What movie title best describes your life?",
"What age do you want to live to?",
"What kind of art do you enjoy most?",
"What takes up too much of your time?",
"What do you wish you knew more about?",
"What’s the best way to start the day?",
"What do you wish you knew more about?",
"How different was your life one year ago?",
"What’s the best single day on the calendar?",
"What are some things you’ve had to unlearn?",
"What’s your favorite genre of book or movie?",
"What’s the farthest you’ve ever been from home?",
"What TV channel doesn’t exist but really should?",
"Where is the most interesting place you’ve been?",
"What fad or trend do you hope comes back?",
"What city would you most like to live in?",
"When was the last time you climbed a tree?",
"What do you consider to be your best find?",
"What is special about the place you grew up?",
"What age do you wish you could permanently be?",
"What’s worth spending more on to get the best?",
"What are you most likely to become famous for?",
"What fictional place would you most like to go?",
"Where is the most relaxing place you’ve ever been?",
"What have you only recently formed an opinion about?",
"What is the most heartwarming thing you’ve ever seen?",
"What’s the most interesting piece of art you’ve seen?",
"What’s something you like to do the old-fashioned way?",
"Would you rather go hang gliding or whitewater rafting?",
"Who has impressed you most with what they’ve accomplished?",
"How do you relax after a hard day of work?",
"What TV show or movie do you refuse to watch?",
"What job do you think you’d be really good at?",
"What pets did you have while you were growing up?",
"Where would you spend all your time if you could?",
"What would be the most amazing adventure to go on?",
"What would be your ideal way to spend the weekend?",
"What’s the best way a person can spend their time?",
"What one thing do you really want but can’t afford?",
"What is the luckiest thing that has happened to you?",
"What are some small things that make your day better?",
"What’s the best thing that happened to you last week?",
"What are you looking forward to in the coming months?",
"What’s your favorite piece of clothing you own / owned?",
"What is the most annoying habit that other people have?",
"What is the most annoying question that people ask you?",
"What is the most impressive thing you know how to do?",
"What was the best book or series that you’ve ever read?",
"What question would you most like to know the answer to?",
"What are you interested in that most people haven’t heard of?",
"Why did you decide to do the work you are doing now?",
"What state or country do you never want to go back to?",
"Where do you usually go when you when you have time off?",
"What are you most looking forward to in the next 10 years?",
"What game or movie universe would you most like to live in?"]
    quests.each do |quest|
      Vote.create quest: quest
    end
    redirect_to "/"
  end
end
